import { TestBed } from '@angular/core/testing'; import { InpatientStore } from './inpatient.store';
describe('InpatientStore Phase 2 integrity',()=>{let store:InpatientStore;beforeEach(()=>{TestBed.configureTestingModule({});store=TestBed.inject(InpatientStore)});
it('admits a patient and allocates exactly one available bed',()=>{const bed=store.availableBeds()[0];const admission=store.admit({patientId:'p2',patientName:'Rohan Kapoor',admittedAt:new Date().toISOString(),type:'Planned',department:'General Medicine',attendingDoctor:'Dr. Ananya Sen',reason:'Observation',initialDiagnosis:'Fever',notes:''},bed.id);expect(store.beds().find(b=>b.id===bed.id)?.status).toBe('Occupied');expect(admission.allocations.length).toBe(1);expect(()=>store.admit({patientId:'p3',patientName:'Fatima Khan',admittedAt:new Date().toISOString(),type:'Planned',department:'General Medicine',attendingDoctor:'Dr. Ananya Sen',reason:'Observation',initialDiagnosis:'Review',notes:''},bed.id)).toThrowError(/not available/)});
it('preserves allocation history during transfer',()=>{const target=store.availableBeds()[0];store.transfer('adm1',target.id);const a=store.admissions().find(x=>x.id==='adm1')!;expect(a.allocations.length).toBe(2);expect(a.allocations[0].endedAt).toBeTruthy();expect(a.allocations[1].endedAt).toBeUndefined()});
it('prevents changes after lab result verification',()=>{store.enterLabResults('lab1',[{test:'Troponin I',value:'0.01',unit:'ng/mL',referenceRange:'<0.04',abnormal:false,enteredBy:'Tech',enteredAt:new Date().toISOString()}]);store.verifyLab('lab1','Pathologist');expect(()=>store.enterLabResults('lab1',[])).toThrowError(/cannot be modified/);expect(store.labOrders().find(o=>o.id==='lab1')?.results[0].verifiedBy).toBe('Pathologist')});
it('preserves a single medication administration outcome',()=>{store.administerMedication('mar1','Administered','Nurse');expect(()=>store.administerMedication('mar1','Missed','Nurse')).toThrowError(/already been recorded/)});
it('prevents conflicting theatre schedules',()=>{const p=store.procedures()[0];expect(()=>store.scheduleProcedure({patientId:'p2',patientName:'Rohan Kapoor',name:'Procedure',doctor:'Dr. Sen',team:['Dr. Sen'],scheduledAt:p.scheduledAt,location:p.theatre!,theatre:p.theatre,durationMinutes:30,indication:'Test',notes:'',status:'Scheduled'})).toThrowError(/conflicts/)});
it('releases the active bed and retains history on discharge',()=>{const bedId=store.admissions()[0].allocations[0].bedId;const summary=store.discharge('adm1',{finalDiagnosis:'Stable angina',treatmentSummary:'Observed and treated',procedures:'None',investigationSummary:'Reviewed',conditionAtDischarge:'Stable',medications:'Aspirin',instructions:'Return for chest pain',followUp:'Cardiology in 7 days',attendingDoctor:'Dr. Vikram Rao'});expect(store.admissions().find(a=>a.id==='adm1')?.status).toBe('Discharged');expect(store.beds().find(b=>b.id===bedId)?.status).toBe('Cleaning');expect(store.admissions()[0].allocations[0].endedAt).toBeTruthy();expect(summary.id).toBeTruthy();expect(store.audit().some(e=>e.action==='DISCHARGE')).toBe(true)});
});
