import { TestBed } from '@angular/core/testing'; import { OperationsStore } from './operations.store';
describe('OperationsStore Phase 3 transactions',()=>{let store:OperationsStore;beforeEach(()=>{TestBed.configureTestingModule({});store=TestBed.inject(OperationsStore)});
it('dispenses stock, writes the ledger and generates one pharmacy invoice',()=>{const before=store.batchQuantity('bat1');const invoice=store.dispense('d1',[{medicineId:'med1',batchId:'bat1',prescribedQuantity:30,dispensedQuantity:30,unitPrice:2.5}],'Pharmacist');expect(store.batchQuantity('bat1')).toBe(before-30);expect(store.stockLedger()[0].type).toBe('Dispense');expect(invoice.items[0].source).toBe('Pharmacy');expect(()=>store.createInvoice('p1','Meera Iyer',[{source:'Pharmacy',sourceId:'d1',description:'Duplicate',quantity:1,unitPrice:1,discount:0,taxRate:0}])).toThrowError(/already been invoiced/)});
it('prevents dispensing above prescribed or available stock',()=>{expect(()=>store.dispense('d1',[{medicineId:'med1',batchId:'bat1',prescribedQuantity:10,dispensedQuantity:11,unitPrice:2.5}],'Pharmacist')).toThrowError(/prescribed/);expect(()=>store.dispense('d1',[{medicineId:'med1',batchId:'bat1',prescribedQuantity:9999,dispensedQuantity:9999,unitPrice:2.5}],'Pharmacist')).toThrowError(/Insufficient/)});
it('supports partial and multiple payments without overpayment',()=>{const id='inv1',balance=store.balance(id);store.pay(id,500,'Cash','CASH');expect(store.invoices().find(i=>i.id===id)?.status).toBe('Partially Paid');store.pay(id,balance-500,'Card','CARD-1');expect(store.invoices().find(i=>i.id===id)?.status).toBe('Paid');expect(()=>store.pay(id,1,'Cash','OVER')).toThrowError()});
it('controls refund amount and records approval in audit',()=>{const p=store.pay('inv1',500,'UPI / Digital Payment','UPI-1');const r=store.requestRefund(p.id,200,'Service cancelled');expect(()=>store.requestRefund(p.id,301,'Too much')).toThrowError(/exceeds/);store.approveRefund(r.id,'Finance Manager');expect(store.refunds()[0].status).toBe('Processed');expect(store.audit().some(e=>e.action==='REFUND_PROCESSED')).toBe(true)});
it('preserves insurance claim status history',()=>{const c=store.submitClaim({patientId:'p1',insuranceId:'pol1',invoiceId:'inv1',claimedAmount:2100,submittedAt:new Date().toISOString(),documentRefs:[]});store.updateClaim(c.id,'Partially Approved',1600,'Co-pay applies');const updated=store.claims()[0];expect(updated.history.length).toBe(2);expect(updated.patientResponsibility).toBe(500)});
it('receives procurement into the same immutable stock ledger',()=>{const before=store.batchQuantity('bat2');store.receivePurchaseOrder('po1',500,'bat2');expect(store.batchQuantity('bat2')).toBe(before+500);expect(store.purchaseOrders()[0].status).toBe('Received')});
});
