import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthStore } from '../../core/auth/auth.store';
@Component({ standalone: true, imports: [ReactiveFormsModule, RouterLink], template: `
<main class="auth-shell"><section class="auth-brand"><div class="brand-mark">✚</div><h1>CarePoint</h1><p>Hospital operations, connected with care.</p><div class="trust"><span>✓ Secure sessions</span><span>✓ Role-based access</span><span>✓ Audit-ready workflows</span></div></section>
<section class="auth-panel"><form class="auth-card" [formGroup]="form" (ngSubmit)="submit()"><div class="mobile-brand"><span class="brand-mark">✚</span> CarePoint</div><p class="eyebrow">WELCOME BACK</p><h2>Sign in to your account</h2><p class="muted">Use your hospital credentials to continue.</p>
<label>Email address <span class="required-indicator">*</span><input type="email" formControlName="email" placeholder="name@hospital.com" autocomplete="username"></label>
@if(form.controls.email.touched && form.controls.email.invalid){<small class="error">Enter a valid email address.</small>}
<label>Password <span class="required-indicator">*</span><input type="password" formControlName="password" placeholder="Enter your password" autocomplete="current-password"></label>
@if(form.controls.password.touched && form.controls.password.invalid){<small class="error">Password must be at least 8 characters.</small>}
<div class="form-row"><label class="check"><input type="checkbox" formControlName="remember"> Keep me signed in</label><a routerLink="/auth/forgot-password">Forgot password?</a></div>
@if(auth.error()){<div class="alert" role="alert">{{auth.error()}}</div>}
<button class="primary wide" [disabled]="auth.loading()">{{auth.loading() ? 'Signing in…' : 'Sign in'}}</button>
<p class="demo">Don't have an account? <a routerLink="/auth/register">Register</a></p></form></section></main>`,
styles: [`:host{display:block;min-height:100vh}.auth-shell{display:grid;grid-template-columns:44% 56%;min-height:100vh}.auth-brand{background:#123b4a;color:#fff;padding:12vh 10%;display:flex;flex-direction:column;justify-content:center}.brand-mark{display:inline-grid;place-items:center;width:48px;height:48px;border-radius:12px;background:#15a68a;color:white;font-size:25px}.auth-brand h1{font-size:42px;margin:20px 0 8px}.auth-brand p{font-size:19px;color:#c9e0e5}.trust{display:grid;gap:16px;margin-top:60px;color:#d9ecef}.auth-panel{display:grid;place-items:center;padding:32px;background:#f7fafb}.auth-card{width:min(430px,100%);background:white;padding:42px;border:1px solid #e2eaed;border-radius:16px;box-shadow:0 8px 30px #123b4a0c}.eyebrow{color:#108873;font-size:12px;font-weight:700;letter-spacing:.12em}.auth-card h2{font-size:28px;margin:8px 0}.auth-card label:not(.check){display:grid;gap:8px;margin-top:22px;font-weight:600}.auth-card label span{color:#c23b3b}.auth-card input:not([type=checkbox]){height:46px;border:1px solid #cad6da;border-radius:8px;padding:0 13px;font:inherit}.form-row{display:flex;justify-content:space-between;align-items:center;margin:20px 0;font-size:14px}.check{display:flex;gap:8px}.wide{width:100%}.error{color:#b42318}.alert{background:#fff0ee;color:#9e2a20;padding:10px;border-radius:7px;margin-bottom:15px}.demo{text-align:center;color:#6d7e84;font-size:12px}.mobile-brand{display:none;font-weight:800}@media(max-width:760px){.auth-shell{display:block}.auth-brand{display:none}.auth-panel{min-height:100vh}.mobile-brand{display:flex;align-items:center;gap:10px;margin-bottom:30px}.mobile-brand .brand-mark{width:36px;height:36px}.auth-card{padding:28px}}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class LoginPage { readonly auth = inject(AuthStore); private fb=inject(FormBuilder); private router=inject(Router); private route=inject(ActivatedRoute); readonly form=this.fb.nonNullable.group({email:['admin@carepoint.test',[Validators.required,Validators.email]],password:['password123',[Validators.required,Validators.minLength(8)]],remember:[false]}); async submit(){this.form.markAllAsTouched();if(this.form.invalid)return;if(await this.auth.login(this.form.getRawValue()))void this.router.navigateByUrl(this.route.snapshot.queryParamMap.get('returnUrl') || '/dashboard');} }
