const secured={security:[{bearerAuth:[]}]};const responses={Unauthorized:{description:'Authentication failed'},Forbidden:{description:'Permission denied'},Validation:{description:'Validation failed'},NotFound:{description:'Resource not found'}};
export const openApiDocument={openapi:'3.1.0',info:{title:'CarePoint Hospital Management API',version:'1.0.0'},servers:[{url:'/api/v1'}],components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',bearerFormat:'JWT'}},schemas:{ApiError:{type:'object',required:['message','code'],properties:{message:{type:'string'},code:{type:'string'},errors:{type:'object',additionalProperties:{type:'array',items:{type:'string'}}}}},PatientInput:{type:'object',required:['firstName','lastName','dob','gender','phone'],properties:{firstName:{type:'string'},middleName:{type:'string'},lastName:{type:'string'},dob:{type:'string',format:'date'},gender:{type:'string'},bloodGroup:{type:'string'},phone:{type:'string'},email:{type:'string',format:'email'},city:{type:'string'},emergencyContact:{type:'string'},allergies:{type:'array',items:{type:'string'}}}}}},paths:{
'/auth/login':{post:{summary:'Authenticate a user',requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['email','password'],properties:{email:{type:'string',format:'email'},password:{type:'string',format:'password'}}}}}},responses:{200:{description:'Authenticated'},401:responses.Unauthorized,422:responses.Validation}}},
'/auth/refresh':{post:{summary:'Rotate a refresh token',responses:{200:{description:'Tokens rotated'},401:responses.Unauthorized}}},'/auth/logout':{post:{...secured,summary:'Revoke the current session',responses:{200:{description:'Logged out'}}}},'/auth/me':{get:{...secured,summary:'Current identity and permissions',responses:{200:{description:'Identity'}}}},'/auth/forgot-password':{post:{summary:'Request password reset instructions',responses:{200:{description:'Uniform accepted response'},422:responses.Validation}}},'/auth/reset-password':{post:{summary:'Consume a one-time reset token',responses:{200:{description:'Password reset'},422:responses.Validation}}},'/auth/change-password':{post:{...secured,summary:'Change the authenticated user password',responses:{200:{description:'Password changed'},422:responses.Validation}}},
'/profile/image':{get:{...secured,summary:'Read current profile image',responses:{200:{description:'Image'},404:responses.NotFound}},post:{...secured,summary:'Upload JPEG, PNG or WebP profile image (maximum 5 MB)',responses:{201:{description:'Image stored'},422:responses.Validation}},delete:{...secured,summary:'Delete current profile image',responses:{200:{description:'Image removed'}}}},
'/patients':{get:{...secured,summary:'Search and page patients',parameters:[{in:'query',name:'page',schema:{type:'integer',minimum:1}},{in:'query',name:'page_size',schema:{type:'integer',minimum:1,maximum:100}},{in:'query',name:'search',schema:{type:'string'}},{in:'query',name:'status',schema:{type:'string',enum:['Active','Inactive']}}],responses:{200:{description:'Patient page'},403:responses.Forbidden}},post:{...secured,summary:'Create patient',requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/PatientInput'}}}},responses:{201:{description:'Patient created'},409:{description:'Conflict'},422:responses.Validation}}},
'/patients/{id}':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],get:{...secured,summary:'Patient details',responses:{200:{description:'Patient'},404:responses.NotFound}},put:{...secured,summary:'Update patient',responses:{200:{description:'Patient updated'},422:responses.Validation}},delete:{...secured,summary:'Archive patient',responses:{200:{description:'Patient archived'},404:responses.NotFound}}},
'/dashboard/summary':{get:{...secured,summary:'Dashboard summary',responses:{200:{description:'Summary'}}}},'/dashboard/patient-trends':{get:{...secured,summary:'Patient registration trends',responses:{200:{description:'Trend series'}}}},'/dashboard/appointments-by-department':{get:{...secured,summary:'Appointment department distribution',responses:{200:{description:'Department series'}}}},'/dashboard/appointment-status':{get:{...secured,summary:'Appointment status distribution',responses:{200:{description:'Status series'}}}},'/dashboard/recent-appointments':{get:{...secured,summary:'Recent appointments',responses:{200:{description:'Appointments'}}}}
}};
